markdown: kramdown
theme: minima
baseurl: ""
highlighter: rouge
include:
  - README.md
  - PrivacyPolicy.md
  - PrivacyPolicy_en.md
  - AssetPolicy.md
  - _posts

kramdown:
  syntax_highlighter: rouge
